# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yolo_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'yolo_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12yolo_service.proto\x12\x0cyolo_service\"3\n\nImageFrame\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"f\n\x0b\x42oundingBox\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\x12\x13\n\x0b\x63lass_label\x18\x05 \x01(\t\x12\x12\n\nconfidence\x18\x06 \x01(\x02\"S\n\x0fPredictionBatch\x12-\n\ndetections\x18\x01 \x03(\x0b\x32\x19.yolo_service.BoundingBox\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x32[\n\x0bYoloService\x12L\n\rPredictStream\x12\x18.yolo_service.ImageFrame\x1a\x1d.yolo_service.PredictionBatch(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolo_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEFRAME']._serialized_start=36
  _globals['_IMAGEFRAME']._serialized_end=87
  _globals['_BOUNDINGBOX']._serialized_start=89
  _globals['_BOUNDINGBOX']._serialized_end=191
  _globals['_PREDICTIONBATCH']._serialized_start=193
  _globals['_PREDICTIONBATCH']._serialized_end=276
  _globals['_YOLOSERVICE']._serialized_start=278
  _globals['_YOLOSERVICE']._serialized_end=369
# @@protoc_insertion_point(module_scope)
