# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import yolo_service_pb2 as yolo__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in yolo_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class YoloServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictStream = channel.stream_stream(
                '/yolo_service.YoloService/PredictStream',
                request_serializer=yolo__service__pb2.ImageFrame.SerializeToString,
                response_deserializer=yolo__service__pb2.PredictionBatch.FromString,
                _registered_method=True)


class YoloServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PredictStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YoloServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictStream': grpc.stream_stream_rpc_method_handler(
                    servicer.PredictStream,
                    request_deserializer=yolo__service__pb2.ImageFrame.FromString,
                    response_serializer=yolo__service__pb2.PredictionBatch.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yolo_service.YoloService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('yolo_service.YoloService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class YoloService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/yolo_service.YoloService/PredictStream',
            yolo__service__pb2.ImageFrame.SerializeToString,
            yolo__service__pb2.PredictionBatch.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
