services:
  prometheus: &prometheus
    image: prom/prometheus:v2.53.4
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - yolo_tonic_network

  grafana: &grafana
    image: grafana/grafana:11.6.0
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_BASIC_ENABLED: false
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_DISABLE_SIGNOUT_MENU: true
      GF_SECURITY_ALLOW_EMBEDDING: true
      GF_SERVER_SERVE_FROM_SUB_PATH: true
      GF_SERVE_FROM_SUB_PATH: true
      PROMETHEUS_HOST: prometheus
      PROMETHEUS_PORT: 9090
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/monitoring_dashboards:/var/lib/grafana/monitoring_dashboards
    networks:
      - yolo_tonic_network
