include:
  - base.yaml

services:
  webcam_capture_app:
    build:
      context: .
      dockerfile: ./webcam_capture/Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_ENVIRONMENT: "production"
      WC_CAMERA__STREAM_FPS: 30
      WC_CAMERA__PREDICTION_FPS: 15
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    devices:
      - /dev/video0:/dev/video0
    depends_on:
      - yolo_prediction_service
      - otel-collector
    networks:
      - yolo_tonic_network

  yolo_prediction_service:
    build:
      context: .
      dockerfile: ./yolo_prediction/Dockerfile
    ports:
      - "50051:50051"
    environment:
      APP_ENVIRONMENT: "production"
      YP_MODEL__ONNX_FILE: "yolov8m.onnx"
      YP_MODEL__NUM_INSTANCES: 8
      YP_MODEL__MODEL_DIR: "/app/models"
      YP_MODEL__MIN_PROBABILITY: 0.55
    networks:
      - yolo_tonic_network

  otel-collector:
    extends:
      file: base.yaml
      service: otel-collector

  prometheus:
    extends:
      file: base.yaml
      service: prometheus

  grafana:
    extends:
      file: base.yaml
      service: grafana

networks:
  yolo_tonic_network:
    name: yolo_tonic_network
