services:
  webcam_capture_app:
    build:
      context: .
      dockerfile: ./webcam_capture/Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_ENVIRONMENT: "production"
      WC_CAMERA__STREAM_FPS: 60
      WC_CAMERA__PREDICTION_FPS: 60
    devices:
      - /dev/video0:/dev/video0
    depends_on:
      - yolo_prediction_service
    networks:
      - yolo_tonic_network_cuda

  yolo_prediction_service:
    build:
      context: .
      dockerfile: ./yolo_prediction/cuda.Dockerfile
    ports:
      - "50051:50051"
    environment:
      APP_ENVIRONMENT: "production"
      YP_MODEL__ONNX_FILE: "yolov8m.onnx"
      YP_MODEL__NUM_INSTANCES: 8
      YP_MODEL__MODEL_DIR: "/app/models"
      YP_MODEL__MIN_PROBABILITY: 0.55

    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - yolo_tonic_network_cuda

networks:
  yolo_tonic_network_cuda:
    name: yolo_tonic_network_cuda
