services:
  webcam_capture_app:
    build:
      context: .
      dockerfile: ./webcam_capture/Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_ENVIRONMENT: "production"
    devices:
      - /dev/video0:/dev/video0

  yolo_prediction_service:
    build:
      context: .
      dockerfile: ./yolo_prediction/Dockerfile
    ports:
      - "50051:50051"
    environment:
      APP_ENVIRONMENT: "production"
      APP_MODEL__ONNX_FILE: "yolov8m.onnx"
      APP_MODEL__NUM_INSTANCES: "5"
      APP_MODEL__MODEL_DIR: "/app/models"
