services:
  webcam_capture_app:
    build:
      context: .
      dockerfile: ./webcam_capture/Dockerfile
    ports:
      - "8000:8000"
    environment:
      APP_ENVIRONMENT: "production"
      APP_VIDEO_STREAM_FPS: 60
      APP_PREDICTION_SERVICE__PREDICTION_FPS: 60
    devices:
      - /dev/video0:/dev/video0
    depends_on:
      - yolo_prediction_service

  yolo_prediction_service:
    build:
      context: .
      dockerfile: ./yolo_prediction/cuda.Dockerfile
    ports:
      - "50051:50051"
    environment:
      APP_ENVIRONMENT: "production"
      APP_MODEL__ONNX_FILE: "yolov8m.onnx"
      APP_MODEL__NUM_INSTANCES: "5"
      APP_MODEL__MODEL_DIR: "/app/models"
      APP_MODEL__MIN_PROBABILITY: 0.55

    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
