{
 "title": "Yolo Prediction Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Camera Frames per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "webcam_capture_camera_fps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Predictions Frame per Second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "webcam_capture_prediction_fps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Median Prediction Duration",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(webcam_capture_prediction_duration_ms_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th Pct Prediction Duration",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(webcam_capture_prediction_duration_ms_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "99th Pct Prediction Duration",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(webcam_capture_prediction_duration_ms_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(webcam_capture_prediction_duration_ms_bucket[$__rate_interval])))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(webcam_capture_prediction_duration_ms_bucket[$__rate_interval])))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(webcam_capture_prediction_duration_ms_bucket[$__rate_interval])))",
     "legendFormat": "90th percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(webcam_capture_prediction_duration_ms_bucket[$__rate_interval])))",
     "legendFormat": "Median"
    }
   ]
  }
 ]
}