name: Build yolo tonic images

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build Webcam Capture service image
        uses: docker/build-push-action@v6
        with:
          context: ./webcam_capture
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/yolo-tonic-webcam-capture:latest
            ghcr.io/${{ github.repository }}/yolo-tonic-webcam-capture:${{ github.sha }}

      - name: Download Yolo model
        run: |
          make download-model

      - name: Build Yolo Prediction service image
        uses: docker/build-push-action@v6
        with:
          context: ./yolo_prediction
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/yolo-tonic-yolo-prediction:latest
            ghcr.io/${{ github.repository }}/yolo-tonic-yolo-prediction:${{ github.sha }}
